name: reviewdog
on: [pull_request]
env:
  REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.TEST2 }}
jobs:
  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.TEST2 }}

