name: Go
on: [pull_request]

env:
  GO111MODULE: on
  REVIEWDOG_GITHUB_API_TOKEN: 57de654cc6da7f29
  
jobs:
  check-app:
    runs-on: ubuntu-latest   
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19  
    
    - uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: latest 

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest
         
    - name: Run revive      
      run: go install github.com/mgechev/revive@latest  

    - name: Run golangci-lint      
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.45.2
 
    - name: Run misspell check spelling     
      run:  go get -u github.com/client9/misspell/cmd/misspell
    
    - name: Run unparam to check for unused params    
      run:  go install mvdan.cc/unparam@latest

    - name: Setup security linter
      run: go install github.com/securego/gosec/v2/cmd/gosec@latest

    - name: Run reviewdog github-check
      continue-on-error: true      
      run: reviewdog -reporter=github-check  

    - name: Run reviewdog pr-review 
      continue-on-error: true     
      run: reviewdog -reporter=github-pr-review
